<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>ROIcon.ico</ApplicationIcon>
    <PackageIcon>ROIcon.ico</PackageIcon>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <FileVersion>4.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="client.cfg" />
    <None Remove="Resources\flush.mp3" />
    <None Remove="UserCFG.ini" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ROIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="client.cfg" />
    <EmbeddedResource Include="Resources\flush.mp3" />
    <EmbeddedResource Include="UserCFG.ini" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="GUI\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Pictures\ROIcon.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>